# Generated by Django 3.2.6 on 2022-03-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0003_auto_20220301_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timeSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomReservation.timeslot'),
        ),
    ]
