# Generated by Django 3.2.10 on 2022-03-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0005_timeslot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='timeSlot',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='name',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomReservation.reservation'),
        ),
    ]
