# Generated by Django 3.2.10 on 2022-03-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0006_auto_20220311_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomReservation.timeslot'),
        ),
    ]
