# Generated by Django 3.2.10 on 2022-03-12 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0007_auto_20220311_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('morning', models.FloatField(default=0, null=True)),
                ('afternoon', models.FloatField(default=0, null=True)),
                ('evening', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conferenceroom',
            name='afternoonFee',
        ),
        migrations.RemoveField(
            model_name='conferenceroom',
            name='eveningFee',
        ),
        migrations.RemoveField(
            model_name='conferenceroom',
            name='morningFee',
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomReservation.roomprice'),
        ),
    ]
