# Generated by Django 3.2.10 on 2022-03-12 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0008_auto_20220312_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phoneNumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomReservation.roomprice'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateOfUse',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 3, 12)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomReservation.timeslot'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='afternoon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='evening',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='morning',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
