# Generated by Django 3.2.6 on 2022-03-14 02:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0010_auto_20220313_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 3, 14)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='roomReservation.conferenceroom'),
        ),
    ]
