# Generated by Django 3.2.6 on 2022-03-16 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0011_auto_20220314_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 3, 16)),
        ),
    ]
