# Generated by Django 3.2.6 on 2022-03-17 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0012_alter_reservation_datereserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/roomImages/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 3, 17)),
        ),
    ]
