# Generated by Django 3.2.6 on 2022-03-23 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0013_auto_20220317_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roomImages/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 3, 23)),
        ),
    ]
