# Generated by Django 3.2.10 on 2022-03-30 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0014_auto_20220323_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 3, 30)),
        ),
    ]
