# Generated by Django 3.2.6 on 2022-04-02 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservation', '0015_alter_reservation_datereserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
    ]
